/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Monitors } from "./assets/components/Monitors";
import { Tv } from "./assets/components/Tv";
import { Guitar } from "./assets/components/Guitar";
import { Chair } from "./assets/components/Chair";
import { Desk } from "./assets/components/Desk";
import { Iphone } from "./assets/components/Iphone";
import { Ps4 } from "./assets/components/Ps4";
import { Bed } from "./assets/components/Bed";
import { Estanteria } from "./assets/components/Estanteria";
import { Keyboard } from "./assets/components/Keyboard";
import { Laptop } from "./assets/components/Laptop";
import { Speakers } from "./assets/components/Speakers";
import { Window } from "./assets/components/Window";

export function Model(props) {
  const { nodes, materials } = useGLTF("./model/myRoom9.glb");
  return (
    <group {...props} dispose={null}>
      <Guitar />
      <Chair />

      <Iphone />
      <Monitors />
      <Desk />
      <Ps4 />
      <Bed />
      <Tv />
      <Speakers />
      <Estanteria />
      <Keyboard />
      <Laptop />
      <Window />

      {/* PLANES */}
      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-0.059, 0, 1.059]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={4.482}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Material}
        position={[-0.059, 0, -2.029]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={4.504}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Material}
        position={[3.09, 0, 1.059]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={4.482}
      />
      <mesh
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Material}
        position={[-3.934, 0, 1.059]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={4.482}
      />
    </group>
  );
}

useGLTF.preload("./model/myRoom9.glb");
